version: '3.3'
services:
  database:
    image: mysql
    volumes:
       - "./sql-scripts:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webster_dictionary
    ports:
      - '3306:3306'
    command: --default-authentification-plugin=mysql_native_password
    restart: unless-stopped
